from .test_stateful_slow import SingleClientSimulator, MultiClientSimulator


def test_1():
    state = SingleClientSimulator(n_clients=1)
    state.add_workflow()
    state.add_input_var_to_workflow()
    state.create_op()
    state.add_op_to_workflow()
    state.add_call_to_workflow()
    state.add_input()
    state.execute_workflow()
    state.execute_workflow()


def test_2():
    state = SingleClientSimulator(n_clients=1)
    state.add_workflow()
    state.create_op()
    state.add_input_var_to_workflow()
    state.add_op_to_workflow()
    state.add_call_to_workflow()
    state.add_input()
    state.execute_workflow()
    state.verify_state()


def test_3():
    state = SingleClientSimulator(n_clients=1)
    state.create_op()
    state.add_workflow()
    state.add_workflow()
    state.rename_func()
    state.create_op()
    state.add_workflow()
    state.create_op()
    state.add_input()
    state.create_op()
    state.add_workflow()
    state.rename_input()
    state.add_workflow()
    state.rename_input()
    state.create_op()
    state.rename_input()
    state.add_input_var_to_workflow()
    state.rename_func()
    state.add_input()
    state.add_op_to_workflow()
    state.rename_input()
    state.add_call_to_workflow()
    state.add_input()
    state.add_input()
    state.add_input_var_to_workflow()
    state.add_op_to_workflow()
    state.rename_func()
    state.add_op_to_workflow()
    state.rename_func()
    state.add_input_var_to_workflow()
    state.rename_func()
    state.rename_func()
    state.rename_input()
    state.rename_func()
    state.rename_func()
    state.add_input()
    state.execute_workflow()
    state.add_op_to_workflow()
    state.add_op_to_workflow()
    state.rename_input()
    state.add_op_to_workflow()
    state.execute_workflow()
    state.rename_input()
    state.add_op_to_workflow()
    state.execute_workflow()
    state.add_op_to_workflow()
    state.rename_func()
    state.add_call_to_workflow()
    state.add_input_var_to_workflow()
    state.rename_func()
    state.rename_func()
    state.execute_workflow()
    state.rename_func()
    state.add_call_to_workflow()
    state.rename_func()
    state.add_op_to_workflow()
    state.add_call_to_workflow()
    state.add_call_to_workflow()
    state.add_input_var_to_workflow()
    state.add_call_to_workflow()
    state.rename_input()
    state.rename_func()
    state.rename_input()
    state.rename_func()
    state.execute_workflow()
    state.add_input_var_to_workflow()
    state.add_op_to_workflow()
    state.add_call_to_workflow()
    state.add_call_to_workflow()
    state.execute_workflow()


def test_4():
    state = SingleClientSimulator(n_clients=1)
    state.create_op()
    state.create_new_version()
    state.rename_func()
    state.add_input()


def test_5():
    state = SingleClientSimulator(n_clients=1)
    state.add_workflow()
    state.add_input_var_to_workflow()
    state.create_op()
    state.add_input()
    state.add_input_var_to_workflow()
    state.add_input_var_to_workflow()
    state.create_new_version()
    state.add_input_var_to_workflow()
    state.add_input()
    state.rename_input()
    state.create_new_version()
    state.add_input_var_to_workflow()
    state.add_op_to_workflow()
    state.rename_input()
    state.add_op_to_workflow()
    state.verify_state()


def test_6():
    state = SingleClientSimulator(n_clients=1)
    state.add_workflow()
    state.create_op()
    state.add_input()
    state.rename_func()
    state.rename_func()
    state.rename_input()
    state.create_op()
    state.add_input()
    state.add_input_var_to_workflow()
    state.add_op_to_workflow()
    state.add_input()
    state.add_op_to_workflow()
    state.add_call_to_workflow()
    state.add_input()
    state.add_op_to_workflow()
    state.execute_workflow()
    state.add_call_to_workflow()
    state.execute_workflow()
    state.verify_state()


def test_7():
    state = SingleClientSimulator(n_clients=1)
    state.create_op()
    state.create_new_version()
    state.rename_func()


def test_8():
    state = MultiClientSimulator(n_clients=3)
    state.create_op()
    state.create_op()
    state.add_input()
    state.add_input()
    state.create_op()
    state.add_input()
    state.add_input()
    state.add_input()
    state.rename_input()
    state.create_op()
    state.add_input()
    state.add_input()
    state.add_input()
    state.rename_input()
    state.add_input()
    state.add_input()


def test_9():
    state = MultiClientSimulator(n_clients=3)
    state.create_op()
    state.rename_input()
    state.sync_one()
    state.sync_one()
    state.add_workflow()
    state.rename_func()
    state.add_workflow()
    state.add_input()
    state.create_new_version()
    state.add_input_var_to_workflow()
    state.add_input()
    state.add_op_to_workflow()
    state.rename_func()
    state.add_call_to_workflow()
    state.execute_workflow()
    state.add_call_to_workflow()
    state.add_input()
    state.add_input_var_to_workflow()
    state.sync_one()


def test_10():
    state = MultiClientSimulator()
    state.add_workflow()
    state.add_input_var_to_workflow()
    state.add_input_var_to_workflow()
    state.add_input_var_to_workflow()
    state.add_input_var_to_workflow()
    state.create_op()
    state.add_op_to_workflow()
    state.add_call_to_workflow()
    state.execute_workflow()
    state.add_input()
    state.sync_one()


def test_11():
    state = MultiClientSimulator(n_clients=3)
    state.add_workflow()
    state.add_input_var_to_workflow()
    state.add_input_var_to_workflow()
    state.create_op()
    state.add_input()
    state.add_op_to_workflow()
    state.add_call_to_workflow()
    state.execute_workflow()
    state.add_input()
    state.sync_one()
    state.verify_state()


def test_12():
    state = MultiClientSimulator(n_clients=3)
    state.add_workflow()
    state.add_input_var_to_workflow()
    state.add_input_var_to_workflow()
    state.create_op()
    state.add_input_var_to_workflow()
    state.add_input_var_to_workflow()
    state.add_op_to_workflow()
    state.add_call_to_workflow()
    state.execute_workflow()
    state.add_input()
    state.sync_one()
    state.verify_state()


def test_13():
    state = MultiClientSimulator(n_clients=3)
    state.create_op()
    state.rename_func()
    state.rename_input()
    state.add_input()
    state.rename_func()
    state.rename_func()
    state.add_input()
    state.create_op()
    state.add_workflow()
    state.check_mock_storage_single()
    state.create_op()
    state.sync_one()
    state.create_op()
    state.add_input()
    state.rename_func()
    state.add_input()
    state.rename_input()
    state.check_mock_storage_single()
    state.rename_func()
    state.create_op()
    state.create_op()
    state.add_input()
    state.create_new_version()
    state.verify_state()
