from .test_stateful import SingleClientSimulator


def test_1():
    state = SingleClientSimulator()
    state.add_workflow()
    state.add_input_var_to_workflow()
    state.create_op()
    state.add_op_to_workflow()
    state.add_call_to_workflow()
    state.add_input()
    state.execute_workflow()
    state.execute_workflow()


def test_2():
    state = SingleClientSimulator()
    state.add_workflow()
    state.create_op()
    state.add_input_var_to_workflow()
    state.add_op_to_workflow()
    state.add_call_to_workflow()
    state.add_input()
    state.execute_workflow()
    state.verify_state()


def test_3():
    state = SingleClientSimulator()
    state.create_op()
    state.add_workflow()
    state.add_workflow()
    state.rename_func()
    state.create_op()
    state.add_workflow()
    state.create_op()
    state.add_input()
    state.create_op()
    state.add_workflow()
    state.rename_input()
    state.add_workflow()
    state.rename_input()
    state.create_op()
    state.rename_input()
    state.add_input_var_to_workflow()
    state.rename_func()
    state.add_input()
    state.add_op_to_workflow()
    state.rename_input()
    state.add_call_to_workflow()
    state.add_input()
    state.add_input()
    state.add_input_var_to_workflow()
    state.add_op_to_workflow()
    state.rename_func()
    state.add_op_to_workflow()
    state.rename_func()
    state.add_input_var_to_workflow()
    state.rename_func()
    state.rename_func()
    state.rename_input()
    state.rename_func()
    state.rename_func()
    state.add_input()
    state.execute_workflow()
    state.add_op_to_workflow()
    state.add_op_to_workflow()
    state.rename_input()
    state.add_op_to_workflow()
    state.execute_workflow()
    state.rename_input()
    state.add_op_to_workflow()
    state.execute_workflow()
    state.add_op_to_workflow()
    state.rename_func()
    state.add_call_to_workflow()
    state.add_input_var_to_workflow()
    state.rename_func()
    state.rename_func()
    state.execute_workflow()
    state.rename_func()
    state.add_call_to_workflow()
    state.rename_func()
    state.add_op_to_workflow()
    state.add_call_to_workflow()
    state.add_call_to_workflow()
    state.add_input_var_to_workflow()
    state.add_call_to_workflow()
    state.rename_input()
    state.rename_func()
    state.rename_input()
    state.rename_func()
    state.execute_workflow()
    state.add_input_var_to_workflow()
    state.add_op_to_workflow()
    state.add_call_to_workflow()
    state.add_call_to_workflow()
    state.execute_workflow()


def test_4():
    state = SingleClientSimulator()
    state.create_op()
    state.create_new_version()
    state.rename_func()
    state.add_input()


def test_5():
    state = SingleClientSimulator()
    state.add_workflow()
    state.add_input_var_to_workflow()
    state.create_op()
    state.add_input()
    state.add_input_var_to_workflow()
    state.add_input_var_to_workflow()
    state.create_new_version()
    state.add_input_var_to_workflow()
    state.add_input()
    state.rename_input()
    state.create_new_version()
    state.add_input_var_to_workflow()
    state.add_op_to_workflow()
    state.rename_input()
    state.add_op_to_workflow()
    state.verify_state()


def test_6():
    state = SingleClientSimulator()
    state.add_workflow()
    state.create_op()
    state.add_input()
    state.rename_func()
    state.rename_func()
    state.rename_input()
    state.create_op()
    state.add_input()
    state.add_input_var_to_workflow()
    state.add_op_to_workflow()
    state.add_input()
    state.add_op_to_workflow()
    state.add_call_to_workflow()
    state.add_input()
    state.add_op_to_workflow()
    state.execute_workflow()
    state.add_call_to_workflow()
    state.execute_workflow()
    state.verify_state()
