from ..common_imports import *
from ..core.config import EnvConfig
from collections import defaultdict
if EnvConfig.has_ray:
    import ray 

def get_uid() -> str:
    """
    Get a random identifier which is unique with high probability from the
    operating system's randomness
    """
    return '{}'.format(binascii.hexlify(os.urandom(16)).decode('utf-8'))

def eq_objs(x:TAny, y:TAny, rtol:float=1e-5, atol:float=1e-8) -> bool:
    """
    A helper function to check when two values are equal. The rules for how
    values can be built are generated by the following:
        - lists, tuples, str-key dicts
        - scalars
        - things like arrays, frames
    """
    numpy_checker = lambda a, b: bool(np.all(np.isclose(a, b, rtol=rtol, atol=atol)))
    tpx, tpy = type(x), type(y)
    if tpx != tpy:
        failure = (f'Different types', x, y)
        return False
    if tpx is np.ndarray:
        result = numpy_checker(x, y)
        return result
    elif tpx is pd.DataFrame:
        return numpy_checker(x, y)
    elif tpx is pd.Series:
        return numpy_checker(x, y)
    elif tpx in (list, tuple):
        if len(x) != len(y):
            return False
        return all(eq_objs(xelt, yelt, rtol=rtol, atol=atol) for xelt, yelt in zip(x, y))
    elif tpx is dict:
        if len(x) != len(y):
            return False
        if x.keys() != y.keys():
            return False
        return all(eq_objs(x=x[k], y=y[k], rtol=rtol, atol=atol) for k in x.keys())
    else:
        return x == y

def all_distinct(elts:TIter[THashable]) -> bool:
    return len(list(elts)) == len(set(elts))

################################################################################
### lists
################################################################################
def concat_lists(lists:TList[list]) -> list:
    return [x for lst in lists for x in lst]

T = typing.TypeVar('T')
def concat_homogeneous_lists(lists:TList[TList[T]]) -> TList[T]:
    return [x for lst in lists for x in lst]

################################################################################
### dicts
################################################################################
_KT = typing.TypeVar('_KT')
_VT = typing.TypeVar('_VT')

# def dictzip(*dcts): 
#     """
#     Returns an iterator over key, value_1, value_2, ... tuples
#     """
#     if not dcts:
#         return
#     for i in set(dcts[0]).intersection(*dcts[1:]):
#         yield (i,) + tuple(d[i] for d in dcts)
# 
# def merge_dicts(*dcts:TDict[_KT, _VT]) -> TDict[_KT, _VT]: 
#     res = {}
#     for dct in dcts:
#         res.update(dct)
#     return res
# 
# def apply_dict(dct:TDict[_KT, _KT], values:TIter[_KT]) -> TList[_KT]:
#     return [dct.get(x, x) for x in values]

def rename_dict_keys(dct:dict, mapping:dict) -> dict:
    return {mapping[k]: v for k, v in dct.items()}

def invert_dict(dct:dict) -> dict:
    return {v: k for k, v in dct.items()}

def compose_dicts(first:dict, second:dict) -> dict:
    return {k: second[v] for k, v in first.items()}


################################################################################
### collection tools
################################################################################
"""
A `Collection` represents a recursive nesting of python lists, dictionaries, and
other values that are of neither of these types.
"""
# TAtom = typing.TypeVar('TAtom') # unclear how to make this work
Collection = TUnion[TAny, TList['Collection'], TDict[str, 'Collection']]


def get_collection_atoms(collection:Collection) -> TList[TAny]:
    """
    Return a list (no guarantees on order) with the atoms in this collection. An
    atom is any element of a list or value of a dict in this collection that is
    itself not a dict or list. 
    """
    if isinstance(collection, list):
        return concat_lists([get_collection_atoms(elt) for elt in collection])
    elif isinstance(collection, dict):
        return concat_lists([get_collection_atoms(v) for v in collection.values()])
    else:
        return [collection]

def collec_same_shape(collec_1:Collection, collec_2:Collection) -> bool:
    """
    Check if two collection objects have the same shape, meaning that all
    matching lists have the same length and all matching dicts have the same
    keys. This takes into account empty internal collections as well.
    """
    if isinstance(collec_1, list):
        if not isinstance(collec_2, list):
            return False
        if not len(collec_1) == len(collec_2):
            return False
        return all(collec_same_shape(elt_1, elt_2) for elt_1, elt_2 in zip(collec_1, collec_2))
    elif isinstance(collec_1, dict):
        if not isinstance(collec_2, dict):
            return False
        if not sorted(collec_1.keys()) == sorted(collec_2.keys()):
            return False
        return all(collec_same_shape(collec_1[k], collec_2[k]) for k in collec_1.keys())
    else:
        if isinstance(collec_2, (list, dict)):
            return False
        return True

def flatten_collection_atoms(collection:Collection, start_idx:int) -> TTuple[TList[TAny], Collection]:
    """
    Given a recursive collection, return a deterministic ordering of its atoms,
    together with a same-shape collection whose atoms are the indices of the
    corresponding atoms in the list.
    """
    if isinstance(collection, list):
        res_flat, res_collec = [], []
        cur_start = start_idx
        for elt in collection:
            elt_flat, elt_collec = flatten_collection_atoms(collection=elt, start_idx=cur_start)
            cur_start += len(elt_flat)
            res_flat += elt_flat
            res_collec.append(elt_collec)
    elif isinstance(collection, dict):
        res_flat, res_collec = [], {}
        ord_keys = sorted(collection.keys())
        cur_start = start_idx
        for k in ord_keys:
            v = collection[k]
            val_flat, val_collec = flatten_collection_atoms(collection=v, start_idx=cur_start)
            cur_start += len(val_flat)
            res_flat += val_flat
            res_collec[k] = val_collec
    else:
        res_flat, res_collec = [collection], start_idx
    return res_flat, res_collec

def unflatten_atoms_like(atoms:TList[TAny], index_reference:Collection) -> Collection:
    """
    Given a list of atoms (non-list and non-dict), and the index of a matching
    collection, unflatten these atoms into a same-shaped collection.
    """
    #! this is too slow to check recursively
    # assert all(not isinstance(atom, (list, dict)) for atom in atoms)
    if isinstance(index_reference, list):
        return [unflatten_atoms_like(atoms=atoms, index_reference=elt) 
                for elt in index_reference]
    elif isinstance(index_reference, dict):
        return {k: unflatten_atoms_like(atoms=atoms, index_reference=v)
                for k, v in index_reference.items()}
    else:
        assert isinstance(index_reference, int)
        return atoms[index_reference]

def apply_to_collection(collection:Collection, func:TCallable[[TAny], TAny]) -> Collection:
    """
    Recursively apply a function to the atoms in a collection, returning a new
    collection of the same shape
    """
    if isinstance(collection, list):
        return [apply_to_collection(collection=elt, func=func) for elt in collection]
    elif isinstance(collection, dict):
        return {k: apply_to_collection(collection=v, func=func) for k, v in collection.items()}
    else:
        return func(collection)
    
################################################################################
### grouping tools. You can do this with pandas but there'd be no types
################################################################################
PatternVar = typing.TypeVar(name='PatternVar')
EltVar = typing.TypeVar(name='EltVar')

def group_like(objs:TList[EltVar], labels:TList[PatternVar]) -> TDict[PatternVar, TList[EltVar]]:
    """
    Group the given objects according to the given pattern values
    """
    assert len(labels) == len(objs)
    res = defaultdict(list)
    for label, obj in zip(labels, objs):
        res[label].append(obj)
    return res

def ungroup_like(groups:TDict[PatternVar, TList[EltVar]], labels:TList[PatternVar]) -> TList[EltVar]:
    """
    Turn groups back into a flat ordering of all elements according to given labels
    """
    assert len(labels) == sum(len(x) for x in groups.values())
    # {label: [indices belonging to this label]}
    index_groups = group_like(objs=list(range(len(labels))), labels=labels)
    res_dict = {index_groups[label][j]: obj
                for label in groups.keys()
                for j, obj in enumerate(groups[label])}
    res = [res_dict[i] for i in range(len(labels))]
    return res

def transpose_lists(lists:TList[TList[TAny]]) -> TList[TList[TAny]]:
    if not lists:
        return []
    assert all(len(lists[0]) == len(lists[i]) for i in range(len(lists)))
    common_len = len(lists[0])
    return [[lists[i][j] for i in range(len(lists))] for j in range(common_len)]

def transpose_returns(returns_cols:TUnion[TList[TAny], TTuple[TList[TAny],...]]) -> TUnion[TList[TTuple[TAny,...]], TList[TAny]]:
    if not isinstance(returns_cols, tuple):
        assert isinstance(returns_cols, list)
        return returns_cols
    else:
        if not returns_cols:
            return []
        assert all(len(returns_cols[0]) == len(returns_cols[i]) for i in range(len(returns_cols)))
        common_len = len(returns_cols[0])
        return [tuple([returns_cols[i][j] for i in range(len(returns_cols))]) for j in range(common_len)]

def transpose_listdict(dictlist:TDict[str, TList[TAny]]) -> TList[TDict[str, TAny]]:
    if not dictlist:
        return []
    k = list(dictlist.keys())[0]
    assert all(len(dictlist[k]) == len(dictlist[other_k]) for other_k in dictlist.keys())
    common_len = len(dictlist[k])
    return [{k: dictlist[k][i] for k in dictlist.keys()} for i in range(common_len) ]

def extract_uniques(objs:TList[TAny], keys:TList[TAny]) -> TTuple[TList[TAny], TList[int], TDict[int, int]]:
    """
    Given lists of objects and matching keys, return:
        - a list of representative objects (one per key)
        - list of indices of these objects in `objs`
        - projection from range(objs) -> range(representatives)
        mapping each object/key to its representative
    """
    assert len(objs) == len(keys)
    (
        unique_keys, # list of unique keys (no guarantee on ordering)
        index, # indices of the unique keys in `keys`
        inverse, # such that unique_keys[inverse] = keys
    ) = np.unique(keys, return_index=True, return_inverse=True)
    representatives = [objs[i] for i in index]
    projection = {i: inverse[i] for i in range(len(objs))}
    return representatives, index.tolist(), projection

# def expand_repeats(uniques:TList[TAny], projection:TDict[int, int]) -> TList[TAny]:
#     num_expanded = len(projection)
#     return [uniques[projection[i]] for i in range(num_expanded)]
    
################################################################################
### (more) mmethod helpers
################################################################################
# def mcall_func(func:TCallable, _mkeys:TList[str], _nout:int, **kwargs):
#     assert set(_mkeys).issubset(set(kwargs.keys()))
#     assert _mkeys
#     mkwargs = {k: kwargs[k] for k in _mkeys}
#     assert all(isinstance(v, list) for v in mkwargs.values())
#     num_calls = len(mkwargs[list(mkwargs.keys())[0]])
#     non_mkwargs = {k: v for k, v in kwargs.items() if k not in _mkeys}
#     non_mkeys = non_mkwargs.keys()
#     results = [[] for _ in range(_nout)]
#     for i in range(num_calls):
#         inputs = {**{k: kwargs[k][i] for k in _mkeys},
#                   **{k: kwargs[k] for k in non_mkeys}}
#         func_returns = func(**inputs)
#         if _nout == 0:
#             pass
#         if _nout == 1:
#             results[0].append(func_returns)
#         elif _nout > 1:
#             assert isinstance(func_returns, tuple)
#             assert len(func_returns) == _nout
#             for j in range(_nout):
#                 results[j].append(func_returns[j])
#     if _nout == 0:
#         return 
#     if _nout == 1:
#         return results[0]
#     elif _nout > 1:
#         return tuple(results)

def chunk_list(lst:TList[TAny], num_chunks:int=None, chunk_size:int=None) -> TList[list]:
    """
    Chunks a list of objects into either approximately-equal chunks of a given
    number, or chunks of an exact given size (with the last one possibly
    smaller).
    """
    n_elts = len(lst)
    assert (num_chunks is None) != (chunk_size is None)
    if num_chunks is not None:
        parts = np.array_split(ary=np.arange(n_elts), indices_or_sections=num_chunks)
        return [[lst[int(i)] for i in part] for part in parts]
    else:
        assert chunk_size is not None
        indices = [i*chunk_size for i in range(1, n_elts // chunk_size + 1)]
        parts = np.array_split(ary=np.arange(n_elts), indices_or_sections=indices)
        return [[lst[int(i)] for i in part] for part in parts if len(part) > 0]

################################################################################
### content hashing 
################################################################################
def is_admissible_atom(obj:TAny, forbidden_types:TList[type]=None) -> bool:
    """
    Recursively check if a value is constituted *only* of certain "simple" types
    """
    forbidden_types = [] if forbidden_types is None else forbidden_types
    tp = type(obj)
    if tp in forbidden_types:
        return False
    if tp in (int, float, str, bool, type(None)):
        return True
    if tp in (list, tuple, set):
        return all([is_admissible_atom(elt, forbidden_types=forbidden_types) for elt in obj])
    if tp is dict:
        return (all([is_admissible_atom(k, forbidden_types=forbidden_types) for k in obj.keys()]) 
                and all([is_admissible_atom(k, forbidden_types=forbidden_types) for k in obj.values()]))
    if tp in (np.ndarray, pd.DataFrame, pd.Series):
        return True
    return False

class ContentHashing(object):

    # @staticmethod
    # def py_md5(value:TAny) -> str:
    #     m = hashlib.md5()
    #     m.update(str(hash(value)).encode())
    #     return m.hexdigest()
    #     
    # @staticmethod
    # def json_md5(value:TAny) -> str:
    #     m = hashlib.md5()
    #     m.update(str(json.dumps(value)).encode())
    #     return m.hexdigest()

    # @staticmethod
    # def dask(obj:TAny) -> str:
    #     """
    #     Dask's hash is not truly deterministic for all objects, for example, try it
    #     on a RandomForestClassifier().
    #     """
    #     return dask.base.tokenize(obj)
    
    @staticmethod
    def joblib_md5(obj:TAny) -> str:
        forbidden_types = [set]
        if not is_admissible_atom(obj=obj, forbidden_types=forbidden_types):
            raise ValueError(f'Got {type(obj)}')
        stream = io.BytesIO()
        joblib.dump(value=obj, filename=stream)
        stream.seek(0)
        m = hashlib.md5()
        m.update(str((stream.read())).encode())
        return m.hexdigest()

    DEFAULT = joblib_md5
        

def causal_push_dict(m, d:TDict[str, str]):
    for k in sorted(d):
        m.update(k.encode())
        m.update(d[k].encode())

################################################################################
### causal hashing
################################################################################
class CausalHashing(object):
    
    @staticmethod
    def update_with_dict(m, d:TDict[str, str]):
        """
        deterministically update a `hashlib.md5()` object with the content of a dictionary.
        """
        for k in sorted(d):
            m.update(k.encode())
            m.update(d[k].encode())

    @staticmethod
    def hash_computation(input_hashes:TDict[str, str], metadata:TDict[str, str]) -> str:
        m = hashlib.md5()
        CausalHashing.update_with_dict(m=m, d=input_hashes)
        CausalHashing.update_with_dict(m=m, d=metadata)
        return m.hexdigest()
    
    @staticmethod
    def hash_outputs(computation_hash:str, output_names:TList[str]) -> str:
        m = hashlib.md5(computation_hash.encode())
        for name in output_names:
            m.update(name.encode())
        return m.hexdigest()

    @staticmethod
    def hashforward_list(cur_hash:str, idx:int) -> str:
        m = hashlib.md5(cur_hash.encode())
        m.update(str(idx).encode())
        return m.hexdigest()

    @staticmethod
    def hashforward_dict(cur_hash:str, key:str) -> str:
        m = hashlib.md5(cur_hash.encode())
        m.update(key.encode())
        return m.hexdigest()

    @staticmethod
    def hashforward_tuple(cur_hash:str, idx:int) -> str:
        m = hashlib.md5(cur_hash.encode())
        m.update(str(idx).encode())
        return m.hexdigest()

    @staticmethod
    def combine_list(elt_hashes:TList[str]) -> str:
        m = hashlib.md5('list'.encode())
        s = str(elt_hashes)
        m.update(s.encode())
        return m.hexdigest()
        
    @staticmethod
    def combine_dict(hashes_dict:TDict[str, str]) -> str:
        m = hashlib.md5('dict'.encode())
        key_order = sorted(hashes_dict)
        s = str([(k, hashes_dict[k]) for k in key_order])
        m.update(s.encode())
        return m.hexdigest()

    @staticmethod
    def combine_tuple(elt_hashes:TTuple[str,...]) -> str:
        m = hashlib.md5('tuple'.encode())
        s = str(elt_hashes)
        m.update(s.encode())
        return m.hexdigest()
